=== wuasjikl-hub/Re-myrpc/Myrpc-core/src/main/resources/myrpc-config.dtd
<?xml version="2.0" encoding="UTF-8" ?>
        <!ELEMENT configuration ANY>
        <!ELEMENT Port ANY>
        <!ELEMENT appName ANY>
        <!ELEMENT registry EMPTY>
        <!ATTLIST registry
                type CDATA #REQUIRED
                Address CDATA #REQUIRED
                >
        <!ELEMENT serializers (serializer+)>
        <!ELEMENT serializer EMPTY>
        <!ATTLIST serializer
                class CDATA #REQUIRED
                name CDATA #REQUIRED
                code CDATA #REQUIRED
                >
        <!ELEMENT serializeType EMPTY>
        <!ATTLIST serializeType
                type CDATA #REQUIRED
                >
                                    <!--表示可添加一个或多个compressor-->
        <!ELEMENT compressors (compressor+)>
        <!ELEMENT compressor EMPTY>
        <!ATTLIST compressor
                class CDATA #REQUIRED
                name CDATA #REQUIRED
                code CDATA #REQUIRED
                >
        <!ELEMENT compressType EMPTY>
        <!ATTLIST compressType
                type CDATA #REQUIRED
                >
        <!ELEMENT loadbalancers (loadbalancer+)>
        <!ELEMENT loadbalancer EMPTY>
        <!ATTLIST loadbalancer
                class CDATA #REQUIRED
                name CDATA #REQUIRED
                code CDATA #REQUIRED
                >
        <!ELEMENT loadBalancerType EMPTY>
        <!ATTLIST loadBalancerType
                type CDATA #REQUIRED
                >
        <!ELEMENT idGenerator EMPTY>
        <!ATTLIST idGenerator
                class CDATA #REQUIRED
                dataCenterId CDATA #REQUIRED
                MachineId CDATA #REQUIRED
                >

=== wuasjikl-hub/Re-myrpc/Myrpc-core/src/main/resources/myrpc.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "myrpc-config.dtd">
<configuration>
    <Port>8003</Port>
    <appName>Myrpc-default</appName>
    <!-- 二选一 -->
    <serializeType type="HESSION"/>
    <serializers>
        <serializer class="com.myrpc.leafe.Serialize.impl.JSONSerializer" name="JSON" code="1"/>
        <serializer class="com.myrpc.leafe.Serialize.impl.JdkSerializer" name="JDK" code="2"/>
        <serializer class="com.myrpc.leafe.Serialize.impl.HessionSerializer" name="HESSION" code="3"/>
    </serializers>
    <!-- 二选一 -->
    <compressType type="Gzip"/>
    <compressors>
        <compressor class="com.myrpc.leafe.compress.impl.GzipCompressor" name="Gzip" code="1"/>
    </compressors>
    <!-- 二选一 -->
    <loadBalancerType type="ConsistentHash"/>
    <registry type="zookeeper" Address="localhost:2181"/>
    <idGenerator class="com.myrpc.leafe.utils.IdGenerator" dataCenterId="2" MachineId="4"/>
</configuration>
